mutation AddUser($input: AddUserInput!) {
    addUser(input: $input) {
        _id
        email
        password
        firstname
        lastname
        role
        phoneNumber
        otp
        newPassword
        passwordResetToken
        passwordResetTokenExpire
        age
        isCompany
        companyName
        companyRegister
        pfp
        birthDate
        cookie
        status
        info
        nickname
        companyPhoneNumber
        createdAt
        updatedAt
    }
}