query GetVideos {
    getVideos {
        _id
        title
        description
        thumbnail
        unitPrice
        level
        category
        youtubeUrl {
            id
            name
            url
        }
        channelTitle
    }
}