mutation UploadVideo($input: VideoUploadInput!) {
    uploadVideo(input: $input) {
        message
        success
        video {
            _id
            title
            description
            thumbnail
            unitPrice
            level
            category
            youtubeUrl {
                id
                name
                url
            }
            channelTitle
        }
    }
}